### ISSUE TITLE
Knjižnice in odvečne datoteke

### ISSUE THREAD

**Issue by jaanos** [LacenS/APPR-2014-15#10]
Programa mi ne zažene, saj v programih `analiza.r` in `animacija.R` pri uvozu knjižnic `"psych"` in `"gridExtra"` navajaš parameter `lib.loc` s potjo, ki je specifična za tvoj sistem. Ti brez tega parametra ne deluje? Če ne, na začetek glavnega programa dodaj vrstico

``` R
.libPaths(c(.libPaths(), "/Library/Frameworks/R.framework/Versions/3.1/Resources/library"))
```

Svetoval bi ti še, da v poročilu napišeš, kako si zgradila prikazane modele, za linearni model pa napiši tudi enačbo premice. Poleg tega so na strani 17 namesto šumnikov vprašaji, tako da bo treba tudi to popraviti.

Mimogrede, slike v obliki `.png` (in nasploh vsa vsebina, ki jo generira tvoj program) ne sodijo na repozitorij. Svetujem ti, da pobrišeš mape `js`, `images` in `analiza/images` skupaj z vsemi datotekami v njih, v datoteko `.gitignore` pa dodaš vrstici (lahko na konec)

```
*.png
js
```

nato pa izbereš vse spremembe (vključno z izbrisanimi slikami) in narediš commit. Ob naslednjem zagonu programa se bodo slike in javascripti spet ustvarili.

**Comment by LacenS** [comment]
Bom popravila.
Hvala!!

**Comment by LacenS** [comment]
Sem popravila vse kar ste rekli, tako da upam da je zdaj ok.
lp

**Comment by jaanos** [comment]
Je v redu, tako da sem posodobil povezavo. Če bi pa še kaj spreminjala, odpri nov issue oziroma ponovno odpri jaanos/APPR-2014-15-zagovori#31. Če se še nisi, se s profesorjem domeni za termin zagovora.
