### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by LacenS** [LacenS/APPR-2014-15#5]
Vsakic, ko uporabim fileEcoding Windows-1252 ali UTF-8 mi R izpise :"invalid input found on input connection"
Tudi, ko sem resevala naloge na tomotu sem morala pri uvozu podatkov crtar fileencoding in na novo odpret datoteko z ASICII encoding, da sem jo lahko oddala.
Imam pa opreacijski sistem OS (mac)
Kako lahko poskrbim, da bo program deloval tudi na drugih racunalnikih?
Hvala

**Comment by jaanos** [comment]
V RStudiu poženi ukaz
```R
system("defaults write org.R-project.R force.LANG en_US.UTF-8")
```
Potem zapri RStudio in ga nazaj odpri, pa bi moralo delovati.

**Comment by LacenS** [comment]
Mislim, da deluje
hvala
