### ISSUE TITLE
Grafi

### ISSUE THREAD

**Issue by LacenS** [LacenS/APPR-2014-15#6]
Iz 7 tabele (ki sem jo sestavila iz 2 tabel) zelim naredit stolpicni graf.
(po letih in procentih)
Nobena funkcija mi ne prime
ggplot mi javlja napako ali mi vrze prazno sliko.

Tudi z risanjem grafov iz drugih tabel imam tezave.
Ali je morda problem v samih tabelah? Ker stevilcne podatke sicer lahko sestevam itd...
Hvala za pomoc
lp

**Comment by LacenS** [comment]
del problema sem ugotovila, da je ta da imam imena stolpcev stevilke...

**Comment by jaanos** [comment]
Če hočeš risati stolpčni graf iz razpredelnice, jo bo treba prej pretvoriti v matriko:
```R
barplot(as.matrix(t7), beside = TRUE)
```
Če bi želela zamenjati osi, bo treba matriko transponirati:
```R
barplot(apply(t7, 1, c), beside = TRUE)
```
Seveda poskrbi še za barve, oznake, legendo itd.

Mimogrede: pazi, da narediš `detach` za vsak `attach`. Trenutno ti program pusti razpredelnici `t1` in `t2` dvakrat pripeti.

**Comment by LacenS** [comment]
Najlepsa hvala!!
lp
