### ISSUE TITLE
Poročilo in slike

### ISSUE THREAD

**Issue by LacenS** [LacenS/APPR-2014-15#9]
Pri risanju zemljevidov sem s funkcijo "par()" 3 zemljevide "zdruzila" v enega..da se lažje vidi primerjava
ali je kakšna možnost, da jih kot 1 sliko tudi vključim v poročilo, ker zdaj mi izriše samo enega. Ali je lažje, da narišem vsakega posebej ?
(sicer še poročilo ni končano, moram uredit da bo grafe izrisalo na pravih mestih, itd...)
Hvala

**Comment by jaanos** [comment]
Za dodajanje PDF-jev z več stranmi lahko uporabiš paket `pdfpages` in ukaz `\includepdf`, npr.
```LaTeX
\includepdf[pages={1-3},nup=1x3]{../slike/zemljevid1.pdf}
```
S parametrom `pages` specificiraš obseg strani, ki jih želiš vključiti, z `nup`pa določiš število stolpcev `x` število vrstic, kamor razporediš strani tvojega PDF-ja. Vsaka tako vključena slika bo na svoji strani, tako da v tem primeru ni smiselno uporabiti okolja `figure` oziroma `sidewaysfigure` (mimogrede, pri prvem zemljevidu začneš z enim in končaš z drugim okoljem). Seveda pa jih je smiselno uporabiti pri slikah, vključenih z `\includegraphics` (ali pa vsaj pusti prazno vrstico pred njimi, da bodo v svojem odstavku).

Za okolje `sidewaysfigure` moraš sicer vključiti paket `rotating`. Vključi tudi paket `hyperref`, da bosta delovala ukaza `\url` in `\href`. Pri predzadnjem spletnem naslovu v seznamu ti manjka `}`, zaradi česar se poročilo ne prevede.

Izgleda, kot da hočeš uporabljati `\-` za novo vrstico. Ta ukaz lahko uporabiš, da dopoveš, kje se lahko besede delijo, če pa hočeš začeti nov odstavek, pa enostavno pustiš prazno vrstico pred njim. Če samo želiš v novo vrstico, ne da bi začela nov odstavek, lahko uporabiš ukaz `\\`.

Mimogrede, pri ukazu `plot` ni potrebno uporabiti še `print` - zato ti vsakič izpiše `NULL`.

**Comment by jaanos** [comment]
Še to: glede na to, da imaš v petek predstavitev, te prosim, da **do srede** (še raje pa že jutri) poskrbiš, da bo na GitHub naložena delujoča različica tvojega programa in poročila.

**Comment by LacenS** [comment]
Hvala za pomoč!
Če prav razumem to pomeni, da moram še samo popravit poročilo in print pri plot? In ali sem s tem zajela vse kar smo morali naredit do 3 faze?
Bom uredila še danes.
lp

**Comment by jaanos** [comment]
Tako je.

Morda samo še ena pripomba: v `zemljevid2.pdf` imaš dva zemljevida, ki se razlikujeta samo v tem, katere države so označene. Smiselno bi bilo imeti en sam zemljevid z obema tipoma oznak - dodaš lahko še eno legendo, kjer pojasniš ti oznaki. Glede na to, da gre barvna lestvica od bele do modre, bi bilo smiselno tudi, da bele pike zamenjaš s kako drugo barvo.

**Comment by LacenS** [comment]
Hvala
bom spremenila

**Comment by LacenS** [comment]
Na githubu je zdaj delujoča verzija do 3 faze.
lp

**Comment by jaanos** [comment]
OK, zdaj je v redu. Edino ena malenkost: ko izpisuješ, kaj rišeš v `slike.R`, imaš namesto nekaterih šumnikov vprašaje.

**Comment by LacenS** [comment]
Bom pustila tako za predstavitev, da ne rabite posodabljat in bom popravila v končni verziji.
lp
